### ISSUE TITLE
new json struct

### ISSUE THREAD

**Issue by minamiokka** [dojyorin/ff14_cafeteria#1]
{
    "name": "",
    "icon": "",
    "thumbnail": "",
    "world": "",
    "address": "",
    "twitter": "",
    "beginner": false,
    "owner": "",
    "id": 0,
    "description": "",
    "comment": "",
    "open": {
        [
          {
            "time": "23時ー25時",
            "dayofweek": "月曜日"
          },
          {
            "time": "23時ー26時",
            "dayofweek": "金曜日"
          }
        ]
    }
}

**Comment by dojyorin** [comment]
`open`の `{}`が余分かも？
```json
{
    "name": "",
    "icon": "",
    "thumbnail": "",
    "world": "",
    "address": "",
    "twitter": "",
    "beginner": false,
    "owner": "",
    "id": 0,
    "description": "",
    "comment": "",
    "open": [
        {
            "time": "23時-25時",
            "dayofweek": "月曜日"
        },
        {
            "time": "23時-26時",
            "dayofweek": "金曜日"
        }
    ]
}
```

**Comment by dojyorin** [comment]
master branchへ適用しました、提案ありがとう！
